spring:
  application:
    name: microservice-template

  profiles:
    active: dev

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  jmx:
    enabled: false

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  rabbitmq:
    listener:
      simple:
        auto-startup: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: never

  health:
    rabbit:
      enabled: false

logging:
  level:
    root: INFO

    # your code
    com.company: INFO

    # Spring framework noise
    org.springframework: WARN
    org.springframework.boot.autoconfigure: WARN
    org.springframework.context: WARN
    org.springframework.web: WARN

    # Security
    org.springframework.security: WARN

    # Hibernate / JPA
    org.hibernate: WARN
    org.hibernate.validator: WARN

    # Messaging
    org.springframework.amqp: WARN

    # Actuator
    org.springframework.boot.actuate: WARN

    # Tomcat
    org.apache.catalina: WARN
    org.apache.coyote: WARN

sample:
  service:
    url: http://localhost:9999

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: BASIC

rabbitmq:
  enabled: false
